name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this if your default branch is "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Working Directory
        run: pwd

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug file structure
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Build project
        run: npm run build
        working-directory: ./src

      - name: Debug dist folder
        run: ls -R ./src/dist  # Ensure build output is present
        run: pwd

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/dist  # Change this if your build output is in another folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
